import Head from 'next/head';
import axios from 'axios';
import { Video } from '../types';
import VideoCard from '../components/VideoCard';
import NoResults from '../components/NoResults';
interface IProps {
  videos: Video[]
};

const Home = ({ videos }: IProps) => {
  return (
    <div>
      <Head>
        <title>TikTok Clone</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='shortcut icon' href='/images/favicon.ico' />
      </Head>
      <main>
        <div className='flex flex-col gap-10 videos h-full'>
          {videos.length ? (
            videos.map((video: Video) => {
              return <VideoCard key={video._id} post={video}/>
            })
          ) : (
            <NoResults text='No Videos'/>
          )
          }
        </div>
      </main>
      <footer>
      </footer>
    </div>
  )
};

export const getServerSideProps = async () => {
  const { data } = await axios.get('http://localhost:3000/api/post');

  return {
    props: {
      videos: data
    }
  }
};

export default Home
